// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile-icons/IconComparison.tsx": () => import("../components/mockups/mobile-icons/IconComparison.tsx")
};
